apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  workflow_dispatch: {}

jobs:
  build:
    steps:
      - name: action test
        uses: https://bitbucket.saas-preprod.beescloud.com/scm/ct/wf2-java-hello-world.git/.cloudbees/actions/custom-action@main
        with:
          arg-1: |
            Optimus Prime