apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test automation caller test workflow

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

permissions:
  scm-token-org: read

jobs:
  build:
    steps:
    - name: checkout
      uses: cloudbees-io/checkout/.cloudbees/testing # v2
      id: checkout
      with:
        fetch-depth: "0"
        repository: https://bitbucket.saas-preprod.beescloud.com/scm/tes/testprivatebbdc.git
        # token: ${{ secrets.BBDC_PAT}}
        # token-auth-type: bearer

    - name: Print Env
      uses: docker://node:21.7-alpine3.18
      run: |
        echo "PWD: $PWD"
        echo "HOME: $HOME"

    - name: Display outputs
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
        echo Commit ID = ${{ steps.checkout.outputs.commit }}
        echo Ref = ${{ steps.checkout.outputs.ref }}    
