apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test automation caller test workflow

on:
  workflow_dispatch:
  push:
    branches:
    - '**'
jobs:
  build:
    steps:

    - name: Checkout Repository
      uses: cloudbees-io/checkout@v1
      with:
       fetch-depth: "0"

