apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test automation caller test workflow

on:
  workflow_dispatch:
  push:
    branches:
    - '**'
jobs:
  build:
    steps:
    - name: checkout
      continue-on-error: true
      uses: cloudbees-io/checkout@v1
      id: checkout
      with:
        fetch-depth: "0"
        repository: cbp-qa-automation/TestPrivateRepo
        github-server-url: https://github.com

    - uses: docker://alpine:3.20
      name: cat git-config
      run: |
        ls /cloudbees/home/.gitconfig
        cat /cloudbees/home/.gitconfig
        
    - name: Print Env
      uses: docker://node:21.7-alpine3.18
      run: |
        echo "PWD: $PWD"
        echo "HOME: $HOME"

    - name: Display outputs
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        echo Repository URL = ${{ steps.checkout.outputs.repository-url }}
        echo Commit ID = ${{ steps.checkout.outputs.commit }}
        echo Commit URL = ${{ steps.checkout.outputs.commit-url }}
        echo Ref = ${{ steps.checkout.outputs.ref }}    
